# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test - Frontend
    runs-on: ubuntu-latest
    steps:
      # 1: setup node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        working-directory: src/main/frontend
        with:
          node-version: 12

      # 2: Checkout repository in the CWD
      - name: Checkout repository
        uses: actions/checkout@v2
        working-directory: src/main/frontend


      # 3: install NPM dependencies
      - name: Install dependencies
        working-directory: src/main/frontend
        run: npm install

      # 4: run test command
      - name: Run test command
        working-directory: src/main/frontend
        run: npm test
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: srikanthganta/tictactoe
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}